### ISSUE TITLE
🙋 mysql登录失败：java.sql.SQLException: Access denied for user 'root'@'172.27.0.2'

### ISSUE THREAD

**Issue by Ikaros-521** [OrdinaryRoad-Project/ordinaryroad-barrage-fly#40]
## Question Report

- 搜索打开和关闭的 [GitHub 问题](https://github.com/OrdinaryRoad-Project/ordinaryroad-barrage-fly/issues)

请在提交问题之前回答这些问题，谢谢。 | Please answer these questions before submitting them. Thank you.

### 你使用了哪个版本？ | Which version did you use?
1.2.0

### 预期行为 | Expected behavior
正常使用

### 实际行为 | Actual behavior
mysql登录失败
```
ordinaryroad-barrage-fly        | java.sql.SQLException: Access denied for user 'root'@'172.27.0.2' (using password: YES)
ordinaryroad-barrage-fly        |       at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:130) ~[mysql-connector-j-8.0.33.jar!/:8.0.33]
ordinaryroad-barrage-fly        |       at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-j-8.0.33.jar!/:8.0.33]
```

```
2024-10-11 23:09:19 [Entrypoint] MySQL Docker Image 8.0.26-1.2.4-server
2024-10-11 23:09:19 [Entrypoint] Starting MySQL 8.0.26-1.2.4-server
2024-10-11 23:09:20 2024-10-11T15:09:20.197314Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.26) starting as process 1
2024-10-11 23:09:20 2024-10-11T15:09:20.211655Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2024-10-11 23:09:20 2024-10-11T15:09:20.425209Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
2024-10-11 23:09:20 2024-10-11T15:09:20.761239Z 0 [Warning] [MY-013746] [Server] A deprecated TLS version TLSv1 is enabled for channel mysql_main
2024-10-11 23:09:20 2024-10-11T15:09:20.761341Z 0 [Warning] [MY-013746] [Server] A deprecated TLS version TLSv1.1 is enabled for channel mysql_main
2024-10-11 23:09:20 2024-10-11T15:09:20.763764Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
2024-10-11 23:09:20 2024-10-11T15:09:20.763985Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
2024-10-11 23:09:20 2024-10-11T15:09:20.802106Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
2024-10-11 23:09:20 2024-10-11T15:09:20.802276Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.26'  socket: '/var/lib/mysql/mysql.sock'  port: 3306  MySQL Community Server - GPL.
```

yml
```
# 需要的环境变量，其他可以环境变量可看每个目录下的.env文件
# MYSQL_ROOT_PASSWORD（MySQL初始ROOT密码）
# ADMIN_USERNAME（任务管理后台登录用户名，默认admin）
# ADMIN_PASSWORD（任务管理后台登录密码，默认admin）
# SPRING_BOOT_ADMIN_BASE_URL（根据后端部署情况设置Spring Boot Admin的地址）
# SUB_BASE_URL（根据后端部署情况设置Client要连接的WebSocket地址）

version: "3.0"
services:
  ordinaryroad-barrage-fly-mysql:
    image: ordinaryroad-barrage-fly-mysql
    container_name: ordinaryroad-barrage-fly-mysql
    build:
      context: ./ordinaryroad-barrage-fly-mysql
    volumes:
      - $PWD/ordinaryroad-barrage-fly-mysql/etc/my.cnf:/etc/my.cnf
      - $PWD/ordinaryroad-barrage-fly-mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD:
    ports:
      - "33066:3306"
    hostname: ordinaryroad-barrage-fly-mysql
    restart: always

  ordinaryroad-barrage-fly-ui:
    image: ordinaryroad-barrage-fly-ui
    container_name: ordinaryroad-barrage-fly-ui
    environment:
      BASE_URL: http://ordinaryroad-barrage-fly:8080
      SPRING_BOOT_ADMIN_BASE_URL: http://localhost:8080/admin
      SUB_BASE_URL:
    hostname: ordinaryroad-barrage-fly-ui
    restart: always

  ordinaryroad-barrage-fly:
    image: ordinaryroad-barrage-fly
    container_name: ordinaryroad-barrage-fly
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      ADMIN_BASE_URL:
      ADMIN_USERNAME:
      ADMIN_PASSWORD:
    hostname: ordinaryroad-barrage-fly
    restart: always

  ordinaryroad-barrage-fly-nginx:
    image: ordinaryroad-barrage-fly-nginx
    container_name: ordinaryroad-barrage-fly-nginx
    build:
      context: ./ordinaryroad-barrage-fly-nginx
    ports:
      # UI
      - "81:81"
      # Admin
      - "8080:8080"
      # 后端
      - "8081:8081"
      # RSocket
      - "9898:9898"
    hostname: ordinaryroad-barrage-fly-nginx
    depends_on:
      - ordinaryroad-barrage-fly
      - ordinaryroad-barrage-fly-ui
    restart: always

```
### 原因分析（如果可以） | Cause analysis (if possible)
mysql默认配置build 运行后，有无密码都登录失败了

**Comment by 1962247851** [comment]
# 需要的环境变量，其他可以环境变量可看每个目录下的.env文件
# MYSQL_ROOT_PASSWORD（MySQL初始ROOT密码）
# ADMIN_USERNAME（任务管理后台登录用户名，默认admin）
# ADMIN_PASSWORD（任务管理后台登录密码，默认admin）
# SPRING_BOOT_ADMIN_BASE_URL（根据后端部署情况设置Spring Boot Admin的地址）
# SUB_BASE_URL（根据后端部署情况设置Client要连接的WebSocket地址）

这些环境变量配置了吗

**Comment by 1962247851** [comment]
可以在`docker-compose.yaml`同级目录下创建`.env`文件，参考 https://barragefly.ordinaryroad.tech/deploy/#_2-1-4-example

**Comment by Ikaros-521** [comment]
> # 需要的环境变量，其他可以环境变量可看每个目录下的.env文件
> # MYSQL_ROOT_PASSWORD（MySQL初始ROOT密码）
> # ADMIN_USERNAME（任务管理后台登录用户名，默认admin）
> # ADMIN_PASSWORD（任务管理后台登录密码，默认admin）
> # SPRING_BOOT_ADMIN_BASE_URL（根据后端部署情况设置Spring Boot Admin的地址）
> # SUB_BASE_URL（根据后端部署情况设置Client要连接的WebSocket地址）
> 这些环境变量配置了吗

.env已经给了默认配置 
```
# .env
# TODO 根据实际部署情况修改
MYSQL_HOST=127.0.0.1
MYSQL_PORT=3306
MYSQL_DATABASE=or_barrage_fly
MYSQL_USERNAME=root
MYSQL_PASSWORD=
MYSQL_ROOT_PASSWORD=
# TODO 根据实际部署情况修改
SUB_BASE_URL=ws://localhost:9898
# TODO 管理后台的账号密码
ADMIN_USERNAME=admin
ADMIN_PASSWORD=admin
# TODO 根据实际需要修改
JAVA_OPTS="-Xmn256m"
```

**Comment by 1962247851** [comment]
把`.env`内容清空，然后按照文档中需要的环境变量配下试试

**Comment by 1962247851** [comment]
MYSQL_ROOT_PASSWORD这个要配置，然后重新build一下mysql

**Comment by Ikaros-521** [comment]
![image](https://github.com/user-attachments/assets/117f95ad-bf09-4bd2-bc19-c84a77b1283d)
![image](https://github.com/user-attachments/assets/35921bb7-4006-4789-868d-48705187d1d8)
还是一样 绷不住了

**Comment by Ikaros-521** [comment]
> 把mysql data目录删掉再重新build <img alt="image" width="262" src="https://private-user-images.githubusercontent.com/43869694/375821461-c580fca6-6b62-46d4-86c2-a4b5fe8e9c7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NjM0ODIsIm5iZiI6MTcyODY2MzE4MiwicGF0aCI6Ii80Mzg2OTY5NC8zNzU4MjE0NjEtYzU4MGZjYTYtNmI2Mi00NmQ0LTg2YzItYTRiNWZlOGU5YzdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDE2MTMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyZTU5NDk5YjJkMDg2YjVjODU0MDAxNmQyNzA3NDFkNzRkNDdhOTNjMzZlZDE2ZWIwOTQyMGQ5YmYzYzU1MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NhYDT6oJB6qjLssWl-czMgiNgbXc1v2uyhWisBkhfbI">

```
Attaching to ordinaryroad-barrage-fly, ordinaryroad-barrage-fly-mysql, ordinaryroad-barrage-fly-nginx, ordinaryroad-barrage-fly-ui
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/run/desktop/mnt/host/wsl/docker-desktop-bind-mounts/Ubuntu/38b7e1f9fcc82b0dc3b006cdef8804ddb347fb338f3701587c5a36119614f98f" to rootfs at "/var/lib/mysql": mount /run/desktop/mnt/host/wsl/docker-desktop-bind-mounts/Ubuntu/38b7e1f9fcc82b0dc3b006cdef8804ddb347fb338f3701587c5a36119614f98f:/var/lib/mysql (via /proc/self/fd/9), flags: 0x5000: no such file or directory: unknown
```
好家伙 挂载不上了

**Comment by Ikaros-521** [comment]
> 把mysql data目录删掉再重新build <img alt="image" width="262" src="https://private-user-images.githubusercontent.com/43869694/375821461-c580fca6-6b62-46d4-86c2-a4b5fe8e9c7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NjM0ODIsIm5iZiI6MTcyODY2MzE4MiwicGF0aCI6Ii80Mzg2OTY5NC8zNzU4MjE0NjEtYzU4MGZjYTYtNmI2Mi00NmQ0LTg2YzItYTRiNWZlOGU5YzdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDE2MTMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyZTU5NDk5YjJkMDg2YjVjODU0MDAxNmQyNzA3NDFkNzRkNDdhOTNjMzZlZDE2ZWIwOTQyMGQ5YmYzYzU1MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NhYDT6oJB6qjLssWl-czMgiNgbXc1v2uyhWisBkhfbI">

成了！！！感谢大佬
